SmartHome/Controllers/AppUserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartHome.Data.Services;
using SmartHome.Data.ViewModels.Account;
using SmartHome.Data.ViewModels.User;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace SmartHome.Controllers
{
    [Authorize]
    public class AppUserController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IUserService _userService;

        public AppUserController(IAccountService accountService,
                                 IUserService userService)
        {
            _accountService = accountService;
            _userService = userService;
        }

        [Route("User/Profile-Details")]
        public async Task<IActionResult> ProfileDetails()
        {
            var user = await _userService.GetAppUserDetails();
            var data = await _userService.GetHomeUserByEmail(user.Email);
            return View(data);
        }

        [Route("User/Profile-Edit/{id:int:min(1)}")]
        public async Task<IActionResult> ProfileEdit(int id)
        {
            var data = await _userService.GetAppUserById(id);
            if(data == null)
            {
                return View("NotFound");
            }
            return View(data);
        }

        [Route("User/Profile-Edit/{id:int:min(1)}")]
        [HttpPost]
        public async Task<IActionResult> ProfileEdit(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _userService.UpdateAppUser(model, "images/profile/");
                await _userService.UpdateHomeUser(model, "images/profile/");
                if (!result.Succeeded)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return View(model);
                } 
            }
            return RedirectToAction("ProfileDetails");
        }

        [Authorize(Roles = "Control Users")]
        [Route("Members/Edit-User/{id:int:min(1)}")]
        public async Task<IActionResult> Edit(int id)
        {
            var data = await _userService.GetAppUserById(id);
            if (data == null)
            {
                return View("NotFound");
            }
         
            ViewBag.EditUserRoleSuccess = TempData["EditUserRoleSuccess"];
            return View(data);
        }

        [Authorize(Roles = "Control Users")]
        [Route("Members/Edit-User/{id:int:min(1)}")]
        [HttpPost]
        public async Task<IActionResult> Edit(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.UserType == 1)
                {
                    await _userService.UpdateHomeUser(model, "images/profile/");
                    // delete Appuser
                    var Appuser = await _accountService.GetUserByEmail(model.Email);
                    if (Appuser == null)
                    {
                        return View("NotFound");
                    }

                    else
                    {
                        var result = await _userService.DeleteAppUser(Appuser);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("ManageUsers", "HomeUser");
                        }

                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                        return RedirectToAction("ManageUsers", "HomeUser");
                    }
                }

                if (model.UserType == 2)
                {
                    var result = await _userService.UpdateAppUser(model, "images/profile/");
                    await _userService.UpdateHomeUser(model, "images/profile/");
                    if (!result.Succeeded)
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }

                        return View(model);
                    }
                }
            }
            return RedirectToAction("ManageUsers" , "HomeUser");
        }

        [Authorize(Roles = "Control Users")]
        public async Task<IActionResult> Delete(int id)
        {
            var homeUser = await _userService.GetAppUserById(id);
            if (homeUser == null)
            {
                return View("NotFound");
            }

            var Appuser = await _accountService.GetUserByEmail(homeUser.Email);
            if (Appuser == null)
            {
                return View("NotFound");
            }

            else
            {
                var result = await _userService.DeleteAppUser(Appuser);
                if (result.Succeeded)
                {
                    await _userService.DeleteHomeUser(id);
                    return RedirectToAction("ManageUsers", "HomeUser");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return RedirectToAction("ManageUsers", "HomeUser");
            }
        }

        /* -------------------------------------   User/Role Part  -----------------------------------*/
        [Authorize(Roles = "Control Users")]
        [Route("Members/User-Roles")]
        [HttpGet]
        public async Task<IActionResult> ManageUserRole(int id)
        {
            var result = await _userService.GetAppUserById(id);
            var user = await _accountService.GetUserByEmail(result.Email);
            ViewData["userId"] = user.Id;
            ViewData["homeUserId"] = id;
            if (user == null)
            {
                return View("NotFound");
            }
            else
            {
                var model = await _userService.GetRolesofUser(user);
                return View(model);
            }
        }

        [Authorize(Roles = "Control Users")]
        [Route("Members/User-Roles")]
        [HttpPost]
        public async Task<IActionResult> ManageUserRole(List<UserRolesViewModel> model, int id)
        {
            var result = await _userService.GetAppUserById(id);
            var user = await _accountService.GetUserByEmail(result.Email);
            if (user == null)
            {
                return View("NotFound");
            }
            else
            {
                TempData["EditUserRoleSuccess"] = true;
                await _userService.AddRemoveUserInRole(model, user);
                return RedirectToAction("Edit", new { id = id });
            }
        }
    }
}

SmartHome/Controllers/DeviceHistoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SmartHome.Data.Services;
using System.Linq;
using System.Threading.Tasks;

namespace SmartHome.Controllers
{
    [Authorize]
    public class DeviceHistoryController : Controller
    {
        private readonly IDevicesService _devicesService;

        public DeviceHistoryController(IDevicesService devicesService)
        {
            _devicesService = devicesService;
        }

       
        [Route("History/{id:int:min(1)}")]
        public async Task<IActionResult> History(int id)
        {
            var data = await _devicesService.GetHistory(id);
            if (data == null)
            {
                return View("NotFound");
            }
            else if (data.Any(x => x.DeviceId == 1))
            {
                ViewData["SystemName"] = "Home Security";
                ViewData["IconName"] = "fas fa-hotel";
                ViewData["TrueValue"] = "Safe";
                ViewData["FalseValue"] = "Unsafe";
            } 
            
            else if (data.Any(x => x.DeviceId == 3))
            {
                ViewData["SystemName"] = "Fire System";
                ViewData["IconName"] = "fas fa-fire-extinguisher";
                ViewData["TrueValue"] = "Safe";
                ViewData["FalseValue"] = "Fire";
            }  
            
            else if (data.Any(x => x.DeviceId == 4))
            {
                ViewData["SystemName"] = "Smoke System";
                ViewData["IconName"] = "fab fa-gripfire";
                ViewData["TrueValue"] = "Safe";
                ViewData["FalseValue"] = "Smoke";
            }

            else if (data.Any(x => x.DeviceId == 5))
            {
                ViewData["SystemName"] = "Outdoor Light";
                ViewData["IconName"] = "far fa-lightbulb";
                ViewData["TrueValue"] = "On";
                ViewData["FalseValue"] = "Off";
            }


            else if (data.Any(x => x.DeviceId == 38))
            {
                ViewData["SystemName"] = "Garage Security";
                ViewData["IconName"] = "fas fa-warehouse";
                ViewData["TrueValue"] = "Safe";
                ViewData["FalseValue"] = "Unsafe";
            }

            else if (data.Any(x => x.DeviceId == 39 || x.DeviceId == 40))
            {
                if(data.Any(x => x.DeviceId == 39))
                {
                    ViewData["SystemName"] = "Left Parking";
                }
                else 
                {
                    ViewData["SystemName"] = "Right Parking";
                }
                ViewData["IconName"] = "fas fa-parking";
                ViewData["TrueValue"] = "Empty";
                ViewData["FalseValue"] = "Busy";
            }
            else if (data.Any(x => x.DeviceId == 42))
            {
                ViewData["SystemName"] = "Garage Light";
                ViewData["IconName"] = "far fa-lightbulb";
                ViewData["TrueValue"] = "On";
                ViewData["FalseValue"] = "Off";
            }
            return View(data);
        }
    
    

    }
}

SmartHome/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<section>
    <div class="container position-relative px-3 main-container">
        <div class="page-notfound">
            <div class="notfound">
                <div class="notfound-404">
                    <h1>Oops!</h1>
                </div>
                <h2>404 - Page Not Found</h2>
                <p>The page you are looking for might have been removed or its name changed or is temporarily unavailable.</p>
                <a class="btn btn-main" asp-controller="Home" asp-action="index">Go To Homepage</a>
            </div>
        </div>
    </div>
</section>

SmartHome/Views/Shared/_Alert.cshtml
<div id="alert-toast"></div>
<div id="homenotification">
    <input id="homealert" type="checkbox" class="alert-notification d-none" data-id="1" />
    <input id="firealert" type="checkbox" class="alert-notification d-none" data-id="3" />
    <input id="smokealert" type="checkbox" class="alert-notification d-none" data-id="4" />
    <input id="garagealert" type="checkbox" class="alert-notification d-none" data-id="38" />
</div>

SmartHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/images/logo.ico">
    <!--  Font awesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
          asp-fallback-test-class="btn"
          asp-fallback-test-property="display"
          asp-fallback-test-value="inline-block"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <!-- Style -->
    @await RenderSectionAsync("CssStyle", required: false)
    <link rel="stylesheet" href="~/css/site.css">

    <title>@ViewData["Title"] - Smart Home</title>
</head>
<body>

    <partial name="_Sidebar" />
    <main class="position-relative main-section">
        <partial name="_login" />
        @RenderBody()
        <partial name="_Alert" />

    </main>


    <footer class="text-center text-white">
        <div class="text-center p-3">
            &copy; 2022 Copyright Smart Home
        </div>
    </footer>


    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <script src="~/js/Site.js"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/Notification.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {
           $(document).on('change', '.alert-notification', function () {

            $.ajax({
                url: '@Url.Action("SendNotification", "Home")',
                type: "Post",
                data: {
                    checkValue: $(this).is(':checked'),
                    dataId: $(this).attr("data-id"),
                },
                success: function (data) {

                },
                error: function (e) {
                    alert('it broked');
                },

            });
        });
    });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("JsonJs", required: false)

</body>
</html>

SmartHome/Views/Shared/_Login.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<ApplicationUser> _signInManager
@inject Microsoft.AspNetCore.Identity.UserManager<ApplicationUser> _userManager
@if (_signInManager.IsSignedIn(User))
{
    var user = await _userManager.GetUserAsync(User);
    var userName = user.FirstName + " " + user.LastName;
    var userImage = user.UserImageURL;
        <nav class="d-flex justify-content-end justify-content-sm-between align-items-center position-fixed">
            <div id="sidebar-button"
                 class="text-end rounded-pill p-3 text-white sidebar-button">
                <i class="fas fa-bars fs-4 fw-bold"></i>
            </div>

            <div class="d-flex align-items-center pe-3 profile-controller">

                <div id="notif-count" class="drop fa-stack fa-lg me-4 d-inline-block" data-count="0">
                    <a>
                        <i class="fa fa-circle fa-stack-2x main-color"></i>
                        <i class="fa fa-bell fa-stack-1x fa-inverse"></i>
                    </a>

                    <div class="dropdownContain ">
                        <div id="notifcation-container" class="dropOut d-flex flex-column pt-4">

                        </div>
                    </div>
                </div>
                <img src="~/@userImage" class="member-img rounded-circle" />
                <span class="d-none d-sm-inline fs-6 fw-bold m-1 admin-name"> @userName  </span>
            </div>
        </nav>
}

SmartHome/Views/Shared/_Sidebar.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<aside id="sidebar" class="position-fixed position-relative overflow-hidden sidebar active">
    <div class="d-flex align-items-center text-white text-center logo-details mt-2">
        <span class="fs-2 logo-title">Smart Home</span>
        <img src="~/images/background/1.png" class="w-100" alt="" />
    </div>
    <ul class="p-0 mt-2 sidebar-links">
        <li>
            <a id="Home" asp-controller="Home" asp-action="Index" class="btn-active d-flex align-items-center py-3">
                <i class="far fa-home text-center fs-4 text-white"></i>
                <span class="text-white fs-6 item-title">Home Rooms</span>
            </a>
        </li>
        @if (User.IsInRole("Dashboard Admin"))
        {
            <li class="position-relative">

                <a id="Dashboard" asp-controller="Dashboard" asp-action="Dashboard" class="btn-active d-flex align-items-center py-3 active">
                    <i class="far fa-tachometer-alt text-center fs-4 text-white"></i>
                    <span class="text-white fs-6 item-title">Dashboard</span>
                </a>
            </li>
        }
        @if (User.IsInRole("Control Users"))
        {
            <li>
                <a id="Members" asp-controller="HomeUser" asp-action="Members" class="btn-active d-flex align-items-center py-3">
                    <i class="far fa-users text-center fs-4 text-white"></i>
                    <span class="text-white fs-6 item-title">Members</span>
                </a>
            </li>
        }
        @if (User.IsInRole("Dashboard Admin"))
        {
            <li>
                <a id="History" asp-controller="DeviceHistory" asp-action="History" asp-route-id="1" class="btn-active d-flex align-items-center py-3">
                    <i class="fas fa-cog text-center fs-4 text-white"></i>
                    <span class="text-white fs-6 item-title">History</span>
                </a>
            </li>
        }
        <li class="position-absolute bottom-0 log-out">
            <a id="User" asp-controller="AppUser" asp-action="ProfileDetails" class="d-flex align-items-center py-3">
                <i class="fas fa-user-circle ps-4 fs-4 text-white"></i>
                <span class="text-white fs-6 item-title">Profile Edit</span>
            </a>
            <a asp-controller="Account" asp-action="Logout" class="d-flex align-items-center py-3">
                <i class="far fa-sign-out-alt ps-4 fs-4 text-white"></i>
                <span class="text-white fs-6 item-title">Log out</span>
            </a>
        </li>
    </ul>
</aside>

SmartHome/Views/Shared/_SignLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="~/images/logo.ico">
    <!--  Font awesome -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
          asp-fallback-test-class="btn"
          asp-fallback-test-property="display"
          asp-fallback-test-value="inline-block"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <!-- Style -->
    <link rel="stylesheet" href="~/css/site.css">
    <title>@ViewData["Title"] - Smart Home</title>
</head>
<body>
    <main >
        @RenderBody()
    </main>


    <footer class="text-center text-white">
        <div class="text-center p-3">
            &copy; 2022 Copyright Smart Home
        </div>
    </footer>

</body>
</html>